project:
  type: website
  output-dir: docs

website:
  title: "Hope Hahn"
  favicon: logo.jpg
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: blog.qmd
        text: Works
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: simplex
    include-in-header: header.html
    backgroundcolor: "#fafbfb"
    css: styles.css
    toc: true
    page-layout: full

editor: source

