project:
  type: website
  output-dir: docs

website:
  title: "Hope Hahn"
  favicon: logo
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: blog.qmd
        text: Blog
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: sandstone
      #light:
      #dark: cyborg
    backgroundcolor: "#fafbfb"
    css: styles.css
    toc: true
    page-layout: full

editor: source

